### ISSUE TITLE
Issue integrating HelpStack

### ISSUE THREAD

**Issue by hazemhagrass** [happyfoxinc/helpstack-android#21]
Hi,
Each time tried to integrate HelpStack with Android Studio project, I got error fetching artices:
![screenshot from 2015-03-13 23 36 28](https://cloud.githubusercontent.com/assets/3625423/6647708/eff36168-c9d9-11e4-8b50-2e5496af50b3.png)

I noticed that I forgot to add dependencies to my build.gradle script:
```
dependencies {
  compile 'com.tenmiles:helpstack:1.0'
}
```
I added it but I got the following error during build:
```
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find helpstack-android:appcompat_v7:unspecified.
     Searched in the following locations:
         https://jcenter.bintray.com/helpstack-android/appcompat_v7/unspecified/appcompat_v7-unspecified.pom
         https://jcenter.bintray.com/helpstack-android/appcompat_v7/unspecified/appcompat_v7-unspecified.jar
         file:/home/hazemhagrass/android-sdk-linux/extras/android/m2repository/helpstack-android/appcompat_v7/unspecified/appcompat_v7-unspecified.pom
         file:/home/hazemhagrass/android-sdk-linux/extras/android/m2repository/helpstack-android/appcompat_v7/unspecified/appcompat_v7-unspecified.jar
         file:/home/hazemhagrass/android-sdk-linux/extras/google/m2repository/helpstack-android/appcompat_v7/unspecified/appcompat_v7-unspecified.pom
         file:/home/hazemhagrass/android-sdk-linux/extras/google/m2repository/helpstack-android/appcompat_v7/unspecified/appcompat_v7-unspecified.jar
     Required by:
         MixaWallet:app:unspecified > com.tenmiles:helpstack:1.1.1
```

Any help!!

**Comment by anirudh24seven** [comment]
Hey. Sorry that you are finding it difficult to integrate HelpStack. 

By the way, the latest version of HelpStack is 1.1.2. Can you try with that? Meanwhile, I will look deeper into your problem.

**Comment by hazemhagrass** [comment]
Thanks a lot for considering me.
Did you have chance to check it?
Sent using CloudMagic
On Sat, Mar 14, 2015 at 7:26 PM, Hazem Hagrass <hazem.hagrass@badrit.com> wrote:Any news!
Sent using CloudMagic
On Sat, Mar 14, 2015 at 3:07 AM, Anirudh S <notifications@github.com> wrote:Hey. Sorry that you are finding it difficult to integrate HelpStack. 

By the way, the latest version of HelpStack is 1.1.2. Can you try with that? Meanwhile, I will look deeper into your problem.

**Comment by anirudh24seven** [comment]
This seems to be a different problem. 

Can you tell me which Gear you are using? Have you made some modifications too?

Looks like some part of the code is expecting JSON but is instead receiving HTML content as input to it.

**Comment by hazemhagrass** [comment]
Im using helpfox gear.
The issue is in helpstack code not in project. just try to create a new project and add helpstack library in it.
Sent using CloudMagic
On Sun, Mar 15, 2015 at 9:16 PM, Anirudh S <notifications@github.com> wrote:This seems to be a different problem. 

Can you tell me which Gear you are using? Have you made some modifications too?

Looks like some part of the code is expecting JSON but is instead receiving HTML content as input to it.

**Comment by anirudh24seven** [comment]
I understand that the issue occurs when you integrate HelpStack.

I guess you are using HappyFox gear. Do you have a corresponding HappyFox account?

**Comment by hazemhagrass** [comment]
Sure, Should I send you credentials to test with?

On Mon, Mar 16, 2015 at 2:32 PM, Anirudh S <notifications@github.com> wrote:

> I understand that the issue occurs when you integrate HelpStack.
>
> I guess you are using HappyFox gear. Do you have a corresponding HappyFox
> account?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/happyfoxinc/helpstack-android/issues/21#issuecomment-81621995>
> .
>



-- 
Thanks a lot
Hazem Mohammed Hagrass

**Comment by anirudh24seven** [comment]
Yes. You can send them to anirudh@tenmiles.com.

**Comment by hazemhagrass** [comment]
Sorry:
it is working now, the issue that I wass using http protocol instead of https in account_url
